apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keynote-strimzi-streams-subscription
  namespace: keynote-rhmi-demo
spec:
  channel: stable
  name: strimzi-kafka-operator
  source: SOURCE_NAME
  sourceNamespace: openshift-marketplace

